# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: sonat
      POSTGRES_PASSWORD: assignment
      POSTGRES_DB: recycle
    ports:
      - "5432:5432"

  webapp:
    image: webapp-jvm
    depends_on:
      - db
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/recycle
    ports:
      - "8080:8080"

  ui:
    image: ui
    depends_on:
      - webapp
    build:
      context: react-app
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"